### ISSUE TITLE
admin conductor trying to connect before conductor ready

### ISSUE THREAD

**Issue by Connoropolous** [holochain-open-dev/holochain-run-dna#7]
instead of the `sleep`s that are scattered, better to look for deterministic waits, such as the stdout 'Conductor ready' log listener strategy

(node:5891) UnhandledPromiseRejectionWarning: Error: could not connect to holochain conductor, please check that a conductor service is running and available at ws://localhost:1234
    at WebSocket.socket.onerror (/Users/connor/code/rsm/acorn-hc/node_modules/@holochain-open-dev/holochain-run-dna/dist/main.js:8052:24)
    at WebSocket.onError (/Users/connor/code/rsm/acorn-hc/node_modules/ws/lib/event-target.js:140:16)
    at WebSocket.emit (events.js:223:5)
    at ClientRequest.<anonymous> (/Users/connor/code/rsm/acorn-hc/node_modules/ws/lib/websocket.js:579:15)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:5891) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by Connoropolous** [comment]
I've just hacked my lib to use timeout 2000 right now, as a workaround

**Comment by Connoropolous** [comment]
over in acorn-release, I've been doing something like...

```
await new Promise((resolve, _reject) => {
    holochain_handle.stdout.on('data', (data) => {
      log('info', 'holochain: ' + data.toString())
      if (data.toString().indexOf(MAGIC_READY_STRING) > -1) {
        resolve()
      }
    })
  })
```
where `holochain_handle` is a child_process.spawn returned value
